name = "Newb Firelight"
version = [0, 1, 8]
min_supported_mc_version = [1, 21, 20]
description = '''
§c%w
§7- An enchanced vanilla shader for Minecraft!
%v
§3https://devendrn.github.io/newb-shader/
''' # %w = patch warning, %v = version
authors = ["JC GAMING7125","devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "b745b8a4-d20c-4214-902e-222cd147a39b" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Actor"]

[info] 
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "ROUNDED_CLOUDS"
materials = ["Clouds"]
description = '''
Rounded Clouds
'''

[[subpack]]
define = "LOW"
materials = ["Clouds","RenderChunk"]
description = '''
low
'''

[[subpack]]
define = "LOW_QUALITY_MULTILAYER_CLOUDS"
materials = ["Clouds","RenderChunk"]
description = '''
Low Quality Multiplayer clouds
(multilayer clouds for low device)
'''

[[subpack]]
define = "MULTILAYER_CLOUD"
materials = ["Clouds"]
description = '''
Multiplayer clouds
(can cause lag for low device)
'''

[[subpack]]
define = "VANILLA_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
Vanilla Clouds
'''

[[subpack]]
define = "COMPLEMENTARY_REMAGINED_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
§2COMPLEMENTARY_REMAGINED_CLOUDS§r
enhance the vanilla clouds
'''

[[subpack]]
define = "APOCALYPSE"
materials = ["Actor","Sky","EndSky","RenderChunk","Clouds"]
description = '''
§4Apocalypse§r
make your game look like zombie apocalypse
'''

[[subpack]]
define = "CHUNK_ANIM"
materials = ["RenderChunk"]
description = '''
Chunk loading animation
'''

[[subpack]]
define = "NO_WAVE_NO_FOG"
materials = ["RenderChunk"]
description = '''
No fog and wave effects
'''

[[subpack]]
define = "NO_FOG"
materials = ["RenderChunk"]
description = '''
No fog effect
'''

[[subpack]]
define = "NO_WAVE"
materials = ["RenderChunk"]
description = '''
No wave effects
'''

[[subpack]]
define = "ALWAYS_REFLECTION"
materials = ["RenderChunk"]
description = '''
Always Reflection 
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''
