name = "Newb Firelight"
version = [0, 1, 7]
min_supported_mc_version = [1, 20, 80]
url = "https://devendrn.github.io/newb-shader/"
authors = ["JC_GAMING7125","devendrn"]
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "Stars", "SunMoon", "RenderChunk", "Actor"]

[description]
# %w = patch warning, %v = version
long = '''
§c%w
§7- An enchanced vanilla shader for Minecraft!
%v
§3https://devendrn.github.io/newb-shader/
'''
short = "Newb Firelight Shader for RenderDragon"

[uuid] # Use https://www.uuidgenerator.net/version4
header = "f02210f0-0cfc-4c53-8146-8966ccdc5008"
module = "b16ab62e-d68c-489d-a73c-1f9670785d34"

[info]
# %a = authors
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
'''
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "ROUNDED_CLOUDS"
materials = ["Clouds"]
description = '''
Rounded Clouds
'''

[[subpack]]
define = "LOW"
materials = ["Clouds","RenderChunk"]
description = '''
low
'''

[[subpack]]
define = "LOW_QUALITY_MULTILAYER_CLOUDS"
materials = ["Clouds","RenderChunk"]
description = '''
Low Quality Multiplayer clouds
(multilayer clouds for low device)
'''

[[subpack]]
define = "MULTILAYER_CLOUD"
materials = ["Clouds"]
description = '''
Multiplayer clouds
(can cause lag for low device)
'''

[[subpack]]
define = "VANILLA_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
Vanilla Clouds
'''

[[subpack]]
define = "COMPLEMENTARY_REMAGINED_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
§3COMPLEMENTARY_REMAGINED_CLOUDS§r
enhance the vanilla clouds
'''

[[subpack]]
define = "CHUNK_ANIM"
materials = ["RenderChunk"]
description = '''
Chunk loading animation
'''

[[subpack]]
define = "NO_WAVE_NO_FOG"
materials = ["RenderChunk"]
description = '''
No fog and wave effects
'''

[[subpack]]
define = "NO_FOG"
materials = ["RenderChunk"]
description = '''
No fog effect
'''

[[subpack]]
define = "NO_WAVE"
materials = ["RenderChunk"]
description = '''
No wave effects
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''
